services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: etnair_user
      POSTGRES_PASSWORD: etnair_pass
      POSTGRES_DB: etnair_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - backend_network
    ports:
      - "5432:5432"

  api:
    image: node:22-alpine
    container_name: etnair_api
    working_dir: /app
    volumes:
      - ./api:/app
    command: sh -c "npm install && npm run dev"
    environment:
      DB_HOST: postgres
      DB_USER: etnair_user
      DB_PASSWORD: etnair_pass
      DB_NAME: etnair_db
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - backend_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - backend_network

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  backend_network:
    driver: bridge
